version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/www"
    schedule:
      interval: "monthly"
    versioning-strategy: increase
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
