name: Website CI

on:
  push:
    paths:
      - "www/**"
  pull_request:
    paths:
      - "www/**"

env:
  NODE: 14.x

defaults:
  run:
    working-directory: "www"

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: "${{ env.NODE }}"

      - name: Set up npm cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-v${{ env.NODE }}-${{ hashFiles('www/package.json') }}-${{ hashFiles('www/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-v${{ env.NODE }}-${{ hashFiles('www/package.json') }}-${{ hashFiles('www/package-lock.json') }}
            ${{ runner.os }}-node-v${{ env.NODE }}-

      - run: java -version

      - name: Install npm dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Upload files
        uses: actions/upload-artifact@v2
        if: success() && github.repository == 'stefankueng/tools' && github.ref == 'refs/heads/main'
        with:
          name: www
          path: ./www/dist/

  deploy:
    runs-on: ubuntu-latest
    needs: tests
    if: github.repository == 'stefankueng/tools' && github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v2

      - name: Download files
        uses: actions/download-artifact@v2
        with:
          name: www
          path: ./www/dist/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: success()
        with:
          allow_empty_commit: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./www/dist/
