name: Website Tests

on:
  push:
    paths:
      - "www/**"
  pull_request:
    paths:
      - "www/**"

env:
  CI: true
  NODE: 12.x

defaults:
  run:
    working-directory: "www"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "${{ env.NODE }}"

      - name: Set up npm cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-v${{ env.NODE }}-${{ hashFiles('www/package.json') }}-${{ hashFiles('www/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-v${{ env.NODE }}-${{ hashFiles('www/package.json') }}-${{ hashFiles('www/package-lock.json') }}
            ${{ runner.OS }}-node-v${{ env.NODE }}-

      - run: java -version

      - name: Install npm dependencies
        run: npm ci

      - name: Run tests
        run: npm test
